language: node_js
node_js:
  - '10'
notifications:
  email:
    on_failure: always
    on_success: never
install:
  - yarn
script:
  - yarn commitlint
  - yarn lint
  - yarn format
  - yarn test
  - yarn build
